[build]
  base = "."
  command = "npm install && npm run build"
  functions = "netlify/functions"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "npm start"
  port = 3000
  targetPort = 3000
  autoLaunch = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200